version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgproj29
      POSTGRES_DB: parserdb
    volumes:
      - ./data:/data
    ports:
      - 5432:5432


  server:
    build:
      context: server/
    container_name: server_app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db

  client:
    build:
      context: client/
    container_name: client_app
    ports:
      - 8000:8000
    depends_on:
      - server

